/**
 * Frozen contract for the browserless slop-convergence instrument probe.
 *
 * WHAT THIS PROBE ASKS
 *
 * The recorded idea (`.omx/ideas.md`, 2026-07-31) is that "AI slop" is not
 * measurable on a single screen but may be measurable as *convergence* across
 * independent generations of one fixed brief: if N agents given the same brief
 * emit N near-identical screens, that is slop, quantified, with no taste
 * judgment involved.
 *
 * Before spending agent-generation money on that question, one cheaper question
 * has to be answered first:
 *
 *   Can a browserless source-level fingerprint separate a set that was built to
 *   converge from a set that was built to diverge?
 *
 * If it cannot, the convergence idea dies here for the price of one script. That
 * negative result is a valid and useful outcome and must be recorded as-is.
 *
 * WHAT THIS PROBE IS NOT
 *
 * It is not a detector, finding, score, criterion, schema, enum, CLI surface,
 * dependency, or network path. It does not measure real AI generations, does not
 * measure whether a compiled guide pack changes output, and does not rank models
 * or executors. It measures an instrument against controls it constructed
 * itself, which is the weakest possible form of evidence and is only useful for
 * killing a bad instrument early.
 */

import { createHash } from "node:crypto";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

/** Git-ignored. Probe results are local evidence, never a public claim. */
export const OUTPUT_ROOT = resolve(REPO_ROOT, ".omx/experiments/slop-convergence-probe-v1");

export const PROBE_ID = "slop-convergence-probe-v1";
export const AGGREGATE_SCHEMA_VERSION = "slop-convergence-probe-v1/aggregate/v1";
export const FINGERPRINT_METHOD_ID = "source-level-structural-fingerprint-v1";
export const DISTANCE_METHOD_ID = "unweighted-mean-of-per-dimension-distance-v1";

/** Deterministic corpus generation. Same seed must always produce the same bytes. */
export const CORPUS_SEED = 20260801;
/**
 * Must not exceed the number of distinct divergent design vocabularies, or the
 * divergent corpus silently contains duplicate-design pairs.
 *
 * Observation 1 ran at 12 against 6 styles and therefore contained six pairs at
 * distance 0, which failed the disjoint-range rule for a corpus reason rather
 * than a metric reason. The size was reduced to consume each pre-existing style
 * exactly once. No style was authored or edited after observation 1; that
 * ordering rule is deliberate and mirrors the Korean judge gate's "no row
 * authoring after the first label" constraint.
 */
export const CORPUS_SIZE = 6;
export const REPEAT_RUNS = 3;

/**
 * The fingerprint dimensions, and how each is compared.
 *
 * `set` dimensions use Jaccard distance (1 - |A n B| / |A u B|).
 * `histogram` dimensions use cosine distance (1 - cosine similarity).
 *
 * Every dimension is derived from HTML source bytes only. None of them is a
 * rendered measurement, so none of them can substitute for the rendered
 * typography/palette/density metrics that already exist in visual-audit.
 */
export const DIMENSIONS = Object.freeze([
  Object.freeze({ id: "tagHistogram", kind: "histogram" }),
  Object.freeze({ id: "classTokens", kind: "set" }),
  Object.freeze({ id: "colorLiterals", kind: "set" }),
  Object.freeze({ id: "fontSizeLiterals", kind: "set" }),
  Object.freeze({ id: "fontWeightLiterals", kind: "set" }),
  Object.freeze({ id: "spacingLiterals", kind: "set" }),
  Object.freeze({ id: "radiusLiterals", kind: "set" }),
  Object.freeze({ id: "layoutModeHistogram", kind: "histogram" })
]);

export const DIMENSION_IDS = Object.freeze(DIMENSIONS.map((dimension) => dimension.id));

/**
 * The decision rule, fixed before the probe runs so the result cannot be tuned
 * after seeing it.
 *
 * The instrument is only considered to discriminate if the divergent control's
 * mean pairwise distance exceeds the convergent control's by at least this
 * margin AND the two ranges do not overlap. Both numbers are arbitrary
 * pre-registrations, not validated thresholds.
 */
export const REQUIRED_MEAN_SEPARATION = 0.25;
export const REQUIRE_DISJOINT_RANGES = true;

export const LIMITATIONS = Object.freeze([
  "Source-level literals are not rendered measurements; a browser resolves cascade, inheritance, and computed values that this probe never sees.",
  "Both control corpora are generated by this probe, so the result shows only that the metric can separate corpora built to differ from corpora built to match.",
  "No real AI generation was observed, so nothing here shows that real generations converge.",
  "No compiled guide pack was applied, so nothing here shows that a guide changes generated output.",
  "The unweighted mean across dimensions is an arbitrary aggregation; no evidence supports that weighting.",
  "Distance from a corpus centroid rewards difference, not quality; a maximally divergent set may be worse UI.",
  "The observation authorizes no detector, criterion, finding, score, schema, enum, CLI surface, or public claim."
]);

/** HTML constructs the fail-closed source extractor refuses to guess about. */
export const UNSUPPORTED_SOURCE_PATTERNS = Object.freeze([
  Object.freeze({ id: "external-stylesheet", pattern: /<link\b[^>]*\brel\s*=\s*["']?stylesheet/i }),
  Object.freeze({ id: "import-rule", pattern: /@import\b/i }),
  Object.freeze({ id: "script-element", pattern: /<script\b/i }),
  Object.freeze({ id: "template-element", pattern: /<template\b/i }),
  Object.freeze({ id: "svg-element", pattern: /<svg\b/i }),
  Object.freeze({ id: "html-comment", pattern: /<!--/ }),
  Object.freeze({ id: "css-comment", pattern: /\/\*/ })
]);

export function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}

export function canonicalJson(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

/**
 * Deterministic PRNG. Corpus generation must be byte-reproducible so the probe
 * can be re-run and hash-compared without storing fixture files.
 */
export function createRandom(seed) {
  let state = seed >>> 0;
  if (state === 0) state = 0x9e3779b9;
  return function next() {
    state ^= state << 13;
    state >>>= 0;
    state ^= state >>> 17;
    state ^= state << 5;
    state >>>= 0;
    return state / 0x100000000;
  };
}

export function pick(random, values) {
  if (!Array.isArray(values) || values.length === 0) {
    throw new Error("pick requires a non-empty array");
  }
  return values[Math.floor(random() * values.length) % values.length];
}
